apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8snginxappsotkust
  namespace: fluxcdtutorial
spec:
  interval: 30s
  path: ./deploy/nginxapp
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-nginxapp-sot      ## ekhane GitRepository metadata.name ke refer korche
